[mnist]
augmentation_pipeline = "image"
transforms = ["normalize", "random_flip"]
batch_size = 64
val_batch_size = 128
epochs = 100
num_classes = 10
img_size = 28
in_channels = 1

[[mnist.augmentations.normalize]]
mean = [0.1307]
std = [0.3081]

[cifar10]
augmentation_pipeline = "image"
transforms = ["normalize", "random_flip"]
batch_size = 64
val_batch_size = 128
epochs = 100
num_classes = 10
img_size = 32
in_channels = 3

[[cifar10.augmentations.normalize]]
mean = [0.4914, 0.4822, 0.4465]
std = [0.2470, 0.2435, 0.2616]

[cifar100]
augmentation_pipeline = "image"
transforms = ["normalize", "random_flip"]
batch_size = 64
val_batch_size = 128
epochs = 100
num_classes = 100
img_size = 32
in_channels = 3

[[cifar100.augmentations.normalize]]
mean = [0.5071, 0.4867, 0.4408]
std = [0.2675, 0.2565, 0.2761]

[fashionmnist]
augmentation_pipeline = "image"
transforms = ["normalize"]
batch_size = 64
val_batch_size = 128
epochs = 100
num_classes = 10
img_size = 28
in_channels = 1

[[fashionmnist.augmentations.normalize]]
mean = [0.1307]
std = [0.3081]

[imagenet1k]
augmentation_pipeline = "image"
transforms = ["normalize", "random_flip"]
batch_size = 32
val_batch_size = 64
epochs = 100
num_classes = 1000
img_size = 224
in_channels = 3

[[imagenet1k.augmentations.normalize]]
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]

[tinyimagenet]
augmentation_pipeline = "image"
transforms = ["normalize", "random_flip", "random_erasing", "random_grayscale"]
# transforms = ["normalize"]
batch_size = 64
val_batch_size = 128
epochs = 100
num_classes = 200
img_size = 64
in_channels = 3

[[tinyimagenet.augmentations.normalize]]
mean = [0.485, 0.456, 0.406]  # Values from imagenet1k
std = [0.229, 0.224, 0.225]

[imagenette2]
augmentation_pipeline = "image"
transforms = ["normalize"]
batch_size = 64
val_batch_size = 128
epochs = 100
num_classes = 200
img_size = 320
in_channels = 3

[[imagenette2.augmentations.normalize]]
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]

[food101]
augmentation_pipeline = "image"
transforms = ["normalize"]
batch_size = 32
val_batch_size = 64
epochs = 100
num_classes = 101
img_size = 96
in_channels = 3

[[food101.augmentations.normalize]]
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]

[modelnet40]
augmentation_pipeline = "cloud"
transforms = []
batch_size = 32
val_batch_size = 64
epochs = 100
num_classes = 40
img_size = 0
in_channels = 3
